SOLUTIONS = [
    {
        "id": "SOL-001",
        "title": "Anomaly Detection Framework",
        "type": "POC",
        "tags": ["time-series", "images", "unsupervised", "python-package"],
        "difficulty": 3,
        "desc": "A generalised anomaly detection library supporting both image and time-series inputs. Benchmarked on 3 internal datasets with >92% recall.",
        "status": "Available",
        "keywords": ["anomaly", "defect", "detection", "quality", "time series", "image"],
    },
    {
        "id": "SOL-002",
        "title": "LLM-based Document Q&A",
        "type": "POC",
        "tags": ["NLP", "RAG", "PDF", "internal-docs"],
        "difficulty": 2,
        "desc": "Retrieval-augmented generation pipeline allowing employees to query large PDF corpora. Achieves 85% answer accuracy on held-out test set.",
        "status": "Available",
        "keywords": ["document", "search", "query", "knowledge", "PDF", "summarise", "text"],
    },
    {
        "id": "SOL-003",
        "title": "Automated Demand Forecasting",
        "type": "POC",
        "tags": ["forecasting", "LSTM", "XGBoost", "time-series"],
        "difficulty": 3,
        "desc": "Hybrid ML model combining gradient boosting and recurrent networks for SKU-level demand forecasting. MAPE reduced by 18% vs. legacy system.",
        "status": "Available",
        "keywords": ["forecast", "demand", "supply", "stock", "inventory", "predict", "sales"],
    },
    {
        "id": "SOL-004",
        "title": "Multimodal Contract Reviewer",
        "type": "Proposal",
        "tags": ["NLP", "LLM", "contracts", "risk"],
        "difficulty": 4,
        "desc": "LLM-powered review pipeline that flags risky clauses, extracts key obligations, and benchmarks against internal standards.",
        "status": "Proposed",
        "keywords": ["contract", "legal", "compliance", "clause", "risk", "document review"],
    },
    {
        "id": "SOL-005",
        "title": "Visual Inspection Co-pilot",
        "type": "POC",
        "tags": ["computer-vision", "real-time", "edge-deployment"],
        "difficulty": 3,
        "desc": "Real-time defect detection on production lines using lightweight CNN deployed on edge hardware. F1-score of 0.94 on pilot line.",
        "status": "Available",
        "keywords": ["inspection", "defect", "manufacturing", "production", "visual", "quality"],
    },
    {
        "id": "SOL-006",
        "title": "Customer Churn Predictor",
        "type": "POC",
        "tags": ["classification", "explainability", "SHAP"],
        "difficulty": 2,
        "desc": "Gradient-boosted classifier with SHAP explainability layer. Identifies at-risk customers 60 days ahead with 78% precision.",
        "status": "Available",
        "keywords": ["churn", "customer", "retention", "marketing", "predict", "attrition"],
    },
]

BU_NEEDS = [
    {
        "id": "BU-001",
        "unit": "Operations — Plant Lyon",
        "title": "Reduce false alarms on sensor lines",
        "desc": "We have hundreds of IoT sensors producing time-series readings. Current rule-based threshold triggers too many false positives. We need a smarter approach.",
        "urgency": "High",
        "keywords": ["anomaly", "time series", "detection", "sensor", "false alarm"],
    },
    {
        "id": "BU-002",
        "unit": "HR — Talent Acquisition",
        "title": "Search through internal policy documents faster",
        "desc": "Our HR team spends hours cross-referencing PDFs of policies. We want to ask questions in plain language and get accurate answers with source references.",
        "urgency": "Medium",
        "keywords": ["document", "PDF", "search", "query", "knowledge", "text"],
    },
    {
        "id": "BU-003",
        "unit": "Supply Chain — Central",
        "title": "Better inventory planning for seasonal SKUs",
        "desc": "Our top 200 SKUs have strong seasonality. We over-order in Q4 and under-order in Q2. We need a forecasting model that can be updated monthly.",
        "urgency": "High",
        "keywords": ["forecast", "inventory", "supply", "stock", "demand", "seasonal", "predict"],
    },
    {
        "id": "BU-004",
        "unit": "Legal — Procurement",
        "title": "Speed up supplier contract review",
        "desc": "Reviewing 50+ contracts per quarter manually is bottleneck. Need automated flagging of non-standard clauses and missing obligations.",
        "urgency": "Medium",
        "keywords": ["contract", "legal", "clause", "review", "compliance", "supplier"],
    },
    {
        "id": "BU-005",
        "unit": "Manufacturing — Bordeaux",
        "title": "Automate visual quality checks on Line 3",
        "desc": "Line 3 produces 3 000 units/day. Manual inspection catches only 70% of surface defects. We want a camera-based system to assist operators.",
        "urgency": "High",
        "keywords": ["inspection", "defect", "visual", "manufacturing", "quality", "production"],
    },
]
